// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1slYbhlGPro9n1lRBPvvW2f_t0XEG8Yw',
    appId: '1:338457827290:web:46566d7f8795af005292e3',
    messagingSenderId: '338457827290',
    projectId: 'eat-sneakers-e8166',
    authDomain: 'eat-sneakers-e8166.firebaseapp.com',
    storageBucket: 'eat-sneakers-e8166.appspot.com',
    measurementId: 'G-LTTC46F2MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEh_DattgzbLJSC2CQFqD9kwjXdICvJZ8',
    appId: '1:338457827290:android:81ac44f7745e35c95292e3',
    messagingSenderId: '338457827290',
    projectId: 'eat-sneakers-e8166',
    storageBucket: 'eat-sneakers-e8166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACwxjcn8ok8Ueu0Kaeqc9CmXdJbuCvAnQ',
    appId: '1:338457827290:ios:a09e29ba63820fa05292e3',
    messagingSenderId: '338457827290',
    projectId: 'eat-sneakers-e8166',
    storageBucket: 'eat-sneakers-e8166.appspot.com',
    iosBundleId: 'com.example.eatSneakers.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACwxjcn8ok8Ueu0Kaeqc9CmXdJbuCvAnQ',
    appId: '1:338457827290:ios:a09e29ba63820fa05292e3',
    messagingSenderId: '338457827290',
    projectId: 'eat-sneakers-e8166',
    storageBucket: 'eat-sneakers-e8166.appspot.com',
    iosBundleId: 'com.example.eatSneakers.RunnerTests',
  );
}
